# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pickup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AudioKit', '~> 2.2'
  use_frameworks!

  # Pods for Pickup

  target 'PickupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
